### ISSUE TITLE
Find and use tool to automatically check docstrings

### ISSUE THREAD

**Issue by hategan** [ExaWorks/psij-python#109]
It may be useful to have a tool that ensures that:
- all parameters of a function/method are documented
- changes to parameters are matched by updates to doctstrings
- docstring links are valid

**Comment by mturilli** [comment]
It might not progress further.

**Comment by hategan** [comment]
Will re-tag for 1.0.0

**Comment by hategan** [comment]
There appears to be no magical tool to do this. Some aspects are covered by enabling strict mode in Sphinx, and some through pep8, but until we get some better tool or idea of a tool on how this could be done, keeping this open will not increase the chances that progress will be made here.
