### ISSUE TITLE
Transform output file paths to absolute.

### ISSUE THREAD

**Issue by hategan** [ExaWorks/psij-python#228]
When specifying output paths, users may be inclined to specify relative names, such as 'stdout.txt'. For the job, these are likely relative to the directory where the job runs, not the directory from which the job was submitted. Before constructing a submit file, PSI/J should attempt to transform relative paths to absolute paths in order to address this.

**Comment by hategan** [comment]
On the other hand, should one be able to specify files that are relative to the job directory and should it be possible to leave the choice of that directory to the scheduler?

@andre-merzky, what do you think?

**Comment by andre-merzky** [comment]
That's a tough one when you consider remote submission.  For local submission either is fine as long as the documentation is clear and (for the second case) the job directory is easy to navigate to.

For remote submission, any translation to an absolute path is likely inconsistent with the remote file system layout.  If one wants to maintain the first option one would need to ensure that the files are staged back - which might not be what the user intended and also may add significant overhead.

So I would opt for interpreting relative paths as relative to the job dir because that is more portable really, but, as said, we need to make it really easy to find that job dir via the API.  We have `get_directory()` for that purpose in the spec, fortunately, which should be returning the location as soon as the job is running.

**Comment by hategan** [comment]
> For remote submission, any translation to an absolute path is likely inconsistent with the remote file system layout. If one wants to maintain the first option one would need to ensure that the files are staged back - which might not be what the user intended and also may add significant overhead.

So globus separated staging from redirection, in the sense that paths for the job were always remote and you needed staging directives to move files from client to remote. Those staging directives also served as maps from the client fs to the remote fs.

This "model" carried over to the rest of the api in Swift.

That's fine in general and I'd be fine with a model like that. But it irks me a bit that this might or should be different when the client fs and job fs are the same. Although it does seem like that would change the semantics based on how the filesystem was organized, and I think that's not quite right.

**Comment by hategan** [comment]
> we need to make it really easy to find that job dir via the API. We have `get_directory()` for that purpose in the spec, fortunately, which should be returning the location as soon as the job is running.

Hmm. I never thought of it that way. In a sense, I am fine with the "remote" side being opaque, at least as far as the job api is concerned, as long as we provide the correct tools to deal with that opacity, such as the staging semantics above. But it is something to think about.

**Comment by andre-merzky** [comment]
> In a sense, I am fine with the "remote" side being opaque, at least as far as the job api is concerned, as long as we provide the correct tools to deal with that opacity, such as the staging semantics above.

I used to be in the same boat, but our users tend to use the file paths on the 'remote' resource directly more often than not: they want to inspect files while a long running simulation is running, check some parts of the output before they even start any staging, etc.  A staging API does not help in those cases, but making paths inspection easy allows them to do all kinds of things out of band `¯\_(ツ)_/¯`

**Comment by hategan** [comment]
> A staging API does not help in those cases, but making paths inspection easy allows them to do all kinds of things out of band

I agree that this is useful, but I'm not sure this belongs in PSIJ. For two reasons. One is that it's fairly easy to solve this as a userland problem (`echo $PWD > ~/job-dir`). And two, which is really one and a half, is that given that this involves manual stuff that has to necessarily happen on a given cluster, you only need to know once what the system defaults to.

If, on the other hand, we're talking about allowing inspections like this to happen remotely, on multiple clusters, then maybe this is something for the layer 1 API or maybe even something entirely different, like some live job inspection toolkit.

**Comment by hategan** [comment]
I tagged this with 1.0.0 not because we want to implement this (we don't), but because we should add a note in the documentation explaining the issue with using relative paths.
