### ISSUE TITLE
Documentation for 1.0.0

### ISSUE THREAD

**Issue by wilke** [ExaWorks/psij-python#252]
Master Task for all documentation issues.

GanttStart: 2022-08-29
GanttDue: 2022-09-18

Subtasks or depends on:
- #106
- #262
- #253 
- #256
- #257

**Comment by hategan** [comment]
We have #106. Is this a duplicate or is this for 1.0.0? If the latter, can we rename it accordingly?

**Comment by wilke** [comment]
GanttStart: 2022-08-29
GanttDue: 2020-09-18


depends on #106

**Comment by wilke** [comment]
> We have #106. Is this a duplicate or is this for 1.0.0? If the latter, can we rename it accordingly?

106 has something task which are not on the critical path. I would like to add all tasks first and merge them later if required.

**Comment by hategan** [comment]
> > We have #106. Is this a duplicate or is this for 1.0.0? If the latter, can we rename it accordingly?
> 
> 106 has something task which are not on the critical path. I would like to add all tasks first and merge them later if required.

Not sure what you mean. #106 is part of the tasks for the 0.1.0 milestone. They should be finished before tasks for 1.0.0. And issues should be named clearly. "Documentation" is too vague and confusing.
