### ISSUE TITLE
Check API Reference

### ISSUE THREAD

**Issue by wilke** [ExaWorks/psij-python#257]
- Proofread autogenerated documentation
- Update or add missing content
- Check coverage for all functions
- move

**Comment by wilke** [comment]
@jameshcorbett Any update? I believe there is a PR for this?

**Comment by j-woz** [comment]
Adding notes here: I can convert these into issues if desired:
https://docs.google.com/document/d/1rKHOPSUpys9wTooSLsisZRGRVUvGqufQ3iP8RbxpEmw
