### ISSUE TITLE
Deploy test suite at NERSC

### ISSUE THREAD

**Issue by wilke** [ExaWorks/psij-python#267]
Setup testing on supported machines, e.g
- Cori **(reporting)**
- Perlmutter

Document setup and report to dashboard.

**Comment by wilke** [comment]
@jameshcorbett Thanks, Cori is reporting daily, I suggest setting host name for the dashboard to cori instead of cori8. Are we adding Perlmutter or should we close the task for now?

**Comment by jameshcorbett** [comment]
I didn't do anything about Cori, that must have been someone else.

**Comment by hategan** [comment]
It would be nice if we could have authentication for the service and a set of admins that can see internal info, such as the email associated with a site.

**Comment by wilke** [comment]
Adding Perlmutter is a target. There is a giltab instance we can use. Adding @mtitov.

**Comment by hategan** [comment]
Cori has been retired and Perlmutter tests are up and running.
