### ISSUE TITLE
Docker compose with flux and psij

### ISSUE THREAD

**Issue by wilke** [ExaWorks/psij-python#274]
Create a docker compose setup for slurm and psij. Have at least one head node and two compute nodes. Install psij and execute successfully hello-flux-container.py

**Comment by mtitov** [comment]
Initial setup of Flux container for PSI/J: https://github.com/mtitov/psij-flux

Test script gives a warning during the job submission
```
/home/fluxuser/.local/lib/python3.7/site-packages/psij/executors/flux.py:141: UserWarning: Flux does not support exclusive_node_use=True, ignoring...
  UserWarning,
```

Also, while trying to list jobs, the following error came up
```
>>> jex.list()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fluxuser/.local/lib/python3.7/site-packages/psij/executors/flux.py", line 180, in list
    return [x["id"] for x in flux.job.job_list(self._fh)]
TypeError: 'JobListRPC' object is not iterable
```

**Comment by mtitov** [comment]
Flux testing environment is ready!

@wilke Andreas, can you please update permissions for a corresponding repo (https://github.com/ExaWorks/containerized-testing-environment), so I will move it there

**Comment by wilke** [comment]
> Flux testing environment is ready!
> 
> 
> 
> @wilke Andreas, can you please update permissions for a corresponding repo (https://github.com/ExaWorks/containerized-testing-environment), so I will move it there

Done

**Comment by mtitov** [comment]
Finalized: https://github.com/ExaWorks/containerized-testing-environment/tree/main/psij/flux

Ticket can be closed
