### ISSUE TITLE
Document the release process on a wiki page

### ISSUE THREAD

**Issue by mturilli** [ExaWorks/psij-python#292]

**Comment by hategan** [comment]
https://github.com/ExaWorks/psi-j-python/wiki/Release-Process-(and-issues-related-to-releases)

**Comment by andre-merzky** [comment]
See [here](https://github.com/ExaWorks/psi-j-python/wiki/Release-Process-(and-issues-related-to-releases))

**Comment by wilke** [comment]
This is partially addressed in https://github.com/ExaWorks/psij-python/pull/311 and should go into web documentation as well. Since the current process is documented I will close the issue for now.
