### ISSUE TITLE
ReadTheDocs needs to follow repo rename

### ISSUE THREAD

**Issue by andre-merzky** [ExaWorks/psij-python#297]
At the moment, RTD builds report:

> Could not send GitHub build status report for psi-j-python. Make sure you have the correct GitHub repository permissions and your [GitHub account](https://readthedocs.org/accounts/social/connections/) is connected to Read the Docs.

I assume that this is caused by the repo rename, but that needs to be checked by an admin for the RTD project...

**Comment by hategan** [comment]
I created a new readthedocs repo named `psij-python` linked to the new psij github repo. I added `andre_merzky` as maintainer. I should probably delete the old project to eliminate confusion. For reference, I tried renaming the old readthedocs project, but it continued to appear under the `psi-j-python` url.

**Comment by andre-merzky** [comment]
The RTD webhook has been migrated with the repo (see https://github.com/ExaWorks/psij-python/settings/hooks/297196744).  I guess that the old RTD project still pulls via that hook, maybe?  I am not too familiar with RTD internals, so that's just a guess...

**Comment by hategan** [comment]
> The RTD webhook has been migrated with the repo (see https://github.com/ExaWorks/psij-python/settings/hooks/297196744). I guess that the old RTD project still pulls via that hook, maybe? I am not too familiar with RTD internals, so that's just a guess...

I kept the old one if we want to copy settings. So both `psi-j-python` and `psij-python` have RTD hooks.

**Comment by hategan** [comment]
Can we close this?

**Comment by andre-merzky** [comment]
Yes!  Thanks
