### ISSUE TITLE
local executor should check env value type

### ISSUE THREAD

**Issue by andre-merzky** [ExaWorks/psij-python#314]
The following code results in an exception:
```py
#!/usr/bin/env python3

import psij

job = psij.Job(psij.JobSpec(executable='/bin/true', environment={'foo':1}))
ex = psij.JobExecutor.get_instance('local')
ex.submit(job)
status = job.wait()
```

The traceback is:

```sh
Traceback (most recent call last):
  File "/mnt/home/merzky/radical/radical.pilot.2/ve3/lib/python3.8/site-packages/psij/executors/local.py", line 216, in submit
    p.process = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1624, in _execute_child
    env_list.append(k + b'=' + os.fsencode(v))
  File "/mnt/home/merzky/radical/radical.pilot.2/ve3/lib/python3.8/os.py", line 804, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not int

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./t.py", line 7, in <module>
    ex.submit(job)
  File "/mnt/home/merzky/radical/radical.pilot.2/ve3/lib/python3.8/site-packages/psij/executors/local.py", line 224, in submit
    raise SubmitException('Failed to submit job', exception=ex)
psij.exceptions.SubmitException: Failed to submit job
```

To some extent that's clearly a user error: env dicts are documented as `str:str` typed, and the user (me) ignored that.  And type checking is for many an anti-pattern in Python.  But, oh boy, this took *way* to long for me to debug as the error message is not really helpful, and I would like to save others from the same time sink.  I would thus propose to either type check the env dict on spec construction, or to simply cast all values to `str`-type.  The latter may still be incorrect in some cases, but is much easier to debug on user level.

**Comment by hategan** [comment]
> I would thus propose to either type check the env dict on spec construction, or to simply cast all values to `str`-type. The latter may still be incorrect in some cases, but is much easier to debug on user level.

Agreed. I think str-ing all values may lead to weirdness in that we may end up with some environment variables set to `<sometype 0xf889383>`. We could and maybe should `str()` integers. We probably shouldn't do so on floats, since there are many ways to represent the same fp value, which may lead to surprising behavior.

**Comment by andre-merzky** [comment]
I think casting some types but not others would be surprising.  I understand the hesitation to cast blindly, that's fair - but then we can also raise a `TypeError` exception and let the user handle it sensibly.

**Comment by hategan** [comment]
> I think casting some types but not others would be surprising. I understand the hesitation to cast blindly, that's fair - but then we can also raise a `TypeError` exception and let the user handle it sensibly.

I agree. I would only have made an exceptions for int due to convenience, since there only seems to be one way to sensibly handle the int case. But yeah, the cost may be a bit of surprise, albeit possibly pleasant in the int case.

**Comment by andre-merzky** [comment]
Yeah, fair reasoning also on the int.  I'm fine either way (raise on non-string, or raise on non-string-or-int).
