### ISSUE TITLE
Release package is incomplete

### ISSUE THREAD

**Issue by andre-merzky** [ExaWorks/psij-python#320]
Reference: [psij-python-0.1.0.post1.tar.gz](https://files.pythonhosted.org/packages/8d/5b/5e7a36d1d8860c43d6cab7f9eaba6febe9b0328d554da200fa5c7d4a0c98/psij-python-0.1.0.post1.tar.gz)

The `setup.py` tries to read `requirements.txt`, but that file is not included in the release.

This issue blocks the creation of a spack package for psij-python which is needed for the SDK release.

**Comment by hategan** [comment]
@yadudoc, this does look a bit like a similar issue we've seen with your machine and Parsl, in that when I run `python3 setup.py sdist`, I get a package that contains requirements.txt, whereas the one published does not.

I'll try to see if I can do a post2.

**Comment by yadudoc** [comment]
Must be something wrong with my build env. At this point, you are probably better off making `0.1.1`.

**Comment by hategan** [comment]
@yadudoc, can you add Andre and I as maintainers on psij-python in pypi, please?

**Comment by yadudoc** [comment]
Please share both of your pypi id's.

**Comment by hategan** [comment]
Mine is "hategan"

**Comment by yadudoc** [comment]
I've added you as an `owner` so you should also be able to add others. Make sure to accept the invite from pypi.

**Comment by hategan** [comment]
Thanks @yadudoc.

I've uploaded 0.1.0.post2. @andre-merzky, can you check now?

**Comment by andre-merzky** [comment]
> Please share both of your pypi id's.

`andre.merzky` - thanks!

> I've uploaded 0.1.0.post2. @andre-merzky, can you check now?

Great, that seems to do the trick! :-)
