### ISSUE TITLE
Flux executor - error in `list` method

### ISSUE THREAD

**Issue by mtitov** [ExaWorks/psij-python#324]
https://github.com/ExaWorks/psij-python/blob/12f8293d53c949ae8f179e7efebc2a3f84fc140f/src/psij/executors/flux.py#L172-L180

Line 180 should be: `return [x["id"] for x in flux.job.job_list(self._fh).get()["jobs"]]`

Example of `flux.job.job_list(self._fh).get()` output:
```
{'jobs': [{'duration': 600.0,
           'exception_occurred': False,
           'expiration': 1671779340.0,
           'id': 326048415744,
           'name': 'hostname',			# executable
           'ncores': 1,
           'nnodes': 1,
           'nodelist': 'flux-sched',		# compute host name
           'ntasks': 1,
           'priority': 16,
           'ranks': '1',
           'result': 1,
           'state': 64,
           'success': True,
           't_cleanup': 1671778740.3368945,
           't_depend': 1671778740.2859387,
           't_inactive': 1671778740.339939,
           't_run': 1671778740.3033786,
           't_submit': 1671778740.2859387,
           'urgency': 16,
           'userid': 1002,
           'waitstatus': 0}]}
```

Flux version:
```
commands:    		0.46.1-54-g17d993060
libflux-core:		0.46.1-54-g17d993060
libflux-security:	0.7.0
broker:  		0.46.1-54-g17d993060
FLUX_URI:		local:///tmp/flux-ah2B0p/local-1
build-options:		+caliper+hwloc==1.11.6+zmq==4.2.5
```

**Comment by hategan** [comment]
Thanks @mtitov. I tagged @jameshcorbett on this. He's the most qualified to comment/review.

**Comment by jameshcorbett** [comment]
Yeah this looks reasonable to me. I was worried that the implementation might return way too many jobs (in which case it should be filtered down to running jobs and should only return the job ID and not all the attributes) but it looks like its filtered on the user ID so it should be fine.

**Comment by mtitov** [comment]
@jameshcorbett Hi James, this issue was discovered within the testing environment, it was the only job I had there, which was used as an example. Thus, cannot confirm that filtering is not needed
