### ISSUE TITLE
Automatic test of (some) documentation code

### ISSUE THREAD

**Issue by hategan** [ExaWorks/psij-python#330]
We would like to automatically test code used in the documentation. That is, there should be a single source for both snippets used in the documentation and what is being tested.

Much of this can be achieved using [literalinclude](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-literalinclude). That is, there should be tests that contain precisely the current code in the docs, possibly one file per snippet, and the snippets in the docs replaced with literalinclude directives that select the relevant lines form the test file.

One difficulty is the use of "<&executor_type>" to render tabs in the docs. This can possibly be solved by making the tabbing javascript code recognize execparams identifiers (i.e., replace `execparams.executor` with the executor string in the tab).

**Comment by RamonAra209** [comment]
![Screen Shot 2023-01-13 at 3 34 26 PM](https://user-images.githubusercontent.com/86633301/212437383-179c4d33-ad2c-49f5-990a-f2215dd26aab.png)

I'm using vscodes html preview, and after using literalinclude for a test, it seems that selecting the executor type is properly rendered without messing with the JavaScript.

Regarding "docs replaced with literalinclude directives that select the relevant lines form the test file", if we go with the one-file-per-test approach, it should negate specifying the line numbers, as it will include all lines from that file. By not specifying, we won't have to periodically go into the rst files and specify the line numbers.

**Comment by RamonAra209** [comment]
Regarding "We would like to automatically test code used in the documentation. That is, there should be a single source for both snippets used in the documentation and what is being tested."

Should I:
1. Place all of the code snippets in the documentation into a "getting-started-snippets" directory
2. literal include those tests where needed by `.. literalinclude:: path-to-getting-started-snippets/<test>`
3. Create a short python script which reads each file within the snippets dir, and produces an aggregate file where each snippet is translated into a pytest testable function?

Is that what you're looking for?

**Comment by hategan** [comment]
> I'm using vscodes html preview, and after using literalinclude for a test, it seems that selecting the executor type is properly rendered without messing with the JavaScript.

That is simply impossible unless the included file is non-functional. In order for the relevant string (e.g., "lsf") to be switched when the tabs are switched, the line has to be `ex = JobExecutor.get_instance("<&executor-type>")`. Since there is no executor named `<&executor-type>`, that will fail if executed. Furthermore, the code examples in the documentation are non-functional snippets: the imports and possibly other boilerplate is missing.

> 
> Regarding "docs replaced with literalinclude directives that select the relevant lines form the test file", if we go with the one-file-per-test approach, it should negate specifying the line numbers, as it will include all lines from that file. By not specifying, we won't have to periodically go into the rst files and specify the line numbers.

Well, no. We don't want to have the import statements or some function whose name starts with `test` appear in the documentation.

**Comment by hategan** [comment]
> Should I:
> 
> 1. Place all of the code snippets in the documentation into a "getting-started-snippets" directory
> 2. literal include those tests where needed by `.. literalinclude:: path-to-getting-started-snippets/<snippet file>`
> 3. Create a short python script which reads each file within the snippets dir, and produces an aggregate file where each snippet is translated into a pytest testable function?
> 
> Is that what you're looking for?

I was thinking more like this:
1. Place fully functional test cases that contain the snippets in the documentation, one file and test for each snippet, into a "tests/docs/getting_started" directory.
2. literal include those tests where needed with literalinclude and specify only the lines that make the snippet (as is currently seen in the documentation) should be shown

Does that make sense?

**Comment by RamonAra209** [comment]
Yes that all makes sense, I'll start working on how you intended it right now.

**Comment by hategan** [comment]
> how you intended it

To clarify: I think this idea was the result of a collaborative effort, so not mine in particular.

**Comment by RamonAra209** [comment]
> I'll update the JS to recognize things like `execparams.executor`

I was wondering if you got around to doing this. If not, could you point me to the correct file to add this change to?

**Comment by hategan** [comment]
> > I'll update the JS to recognize things like `execparams.executor`
> 
> I was wondering if you got around to doing this. If not, could you point me to the correct file to add this change to?

Give me an hour or so.

**Comment by hategan** [comment]
> > > I'll update the JS to recognize things like `execparams.executor`
> > 
> > 
> > I was wondering if you got around to doing this. If not, could you point me to the correct file to add this change to?
> 
> Give me an hour or so.

See PR #335

**Comment by RamonAra209** [comment]
GitHub says in the info section of this open PR: 
> When branches are created from issues, their pull requests are automatically linked.

While that branch is linked here in that info section, when viewing it, GitHub asks me to create a whole new separate PR.

The PR #338
