### ISSUE TITLE
SLURM job wait is None

### ISSUE THREAD

**Issue by j-woz** [ExaWorks/psij-python#358]
On Bebop, I think I am seeing cases where the output files indicate the job is done, but a short job.wait() is returning None, indicating that a final state has not yet been reached.  Could this mean that job.wait() is caching an old scheduler status?

**Comment by hategan** [comment]
Let me guess: the `None` status is in a different process than the one where the job was launched.

It's because the status hasn't been updated yet.

**Comment by j-woz** [comment]
This is the same Python process:
https://github.com/swift-lang/swift-t/blob/7186e7ffeeb358b22d08bc86371d815f5cd74948/turbine/code/scripts/submit/psij/turbine2psij.py#L189

**Comment by hategan** [comment]
My bad. Sorry.

Yes, it is possible. The queue is not polled continuously, so it's entirely possible to have a delay between when the job finishes and when the status is updated.

The queue_polling_interval property in the executor config allows you to adjust the frequency with which the job status is updated.

**Comment by j-woz** [comment]
Using queue_polling_interval works, PSI/J only returns None when not given enough time to poll.
