### ISSUE TITLE
Release 0.9

### ISSUE THREAD

**Issue by mturilli** [ExaWorks/psij-python#367]
Are we ready to release? Based on our past 2 weeks discussions, are we still missing something? If not, should we proceed?

**Comment by hategan** [comment]
I did not make an announcement, but the release is already out on pypi, readthedocs, etc.

I'm thinking that, perhaps, our website should have a bit more pump about this, like list releases and major changes somewhere.

**Comment by hategan** [comment]
Closing since we are past a 0.9 release
