### ISSUE TITLE
Repeated jobs hang indefinitely when using multiprocessing with "fork" start method

### ISSUE THREAD

**Issue by tlhr** [ExaWorks/psij-python#387]
I'm running into odd behavior when launching jobs from a separate process. The first execution seems to work fine, but an additional run in the same python kernel will cause a call to `job.wait()` to hang indefinitely. From a first glance it seems that the `_ProcessReaper.run()` method is not correctly running for subsequent jobs, causing the `job._status_cv` condition to never be notified for additional jobs.

Here is a short script that reproduces the problem:
```python
#!/usr/bin/env python3

import logging
from multiprocessing import Process, set_start_method
import psij


def func():
    # Get logs from PSI/J
    logger = logging.getLogger()
    logger.setLevel("DEBUG")
    logger.addHandler(logging.StreamHandler())

    exe = psij.JobExecutor.get_instance("local")
    job = psij.Job(psij.JobSpec("test", "echo", arguments=["foo"]))
    exe.submit(job)
    print(job, flush=True)

    # This hangs on the second round
    job.wait()
    print(job, flush=True)


if __name__ == "__main__":
    # `fork` hangs, `spawn` and `forkserver` work as expected
    set_start_method("fork")
    p = Process(target=func)
    p.start()
    p.join()

    print("Done, and again...")

    p = Process(target=func)
    p.start()
    p.join()

```

**Comment by hategan** [comment]
Thanks for catching this.

The first process hangs for me.

**Comment by hategan** [comment]
So the first process hangs for me because the reaper thread is started in the parent process but is not really running in the child processes. However, since forking involves a memory copy of the parent process, the variable that is meant to track that the reaper thread is started is set.

When I remove a key piece that lets the reaper be initialized in the subprocess, things seem to work.

So can you give me some more details about which version of PSI/J you are running and perhaps the system on which you are running this?

**Comment by hategan** [comment]
PR #388 is meant to fix the first_process_hanging problem, but I don't think it's a solution for this issue.

**Comment by tlhr** [comment]
> So can you give me some more details about which version of PSI/J you are running and perhaps the system on which you are running this?

Thank you so much for looking into this! The PSI/J version is pulled from master today, but it was also present in the pip package. The python version is 3.10, I can give you more system details tomorrow, I believe it's a recent Ubuntu LTS release.

**Comment by hategan** [comment]
Can you give PR #388 a shot then?

It won't work with fork() if you submit from both parent and child, but it should work if you submit from child processes.

**Comment by tlhr** [comment]
That did the trick, thanks a lot for the quick fix!

**Comment by tlhr** [comment]
Unfortunately there are still some subtle problems here, so I'm reopening this.

First, any executor created in the main process will sabotage executors in child processes (as they still share the reaper thread). Here's an example:
```python
#!/usr/bin/env python3

import logging
from multiprocessing import Process, set_start_method
import psij


def func():
    # Get logs from PSI/J
    logger = logging.getLogger()
    logger.setLevel("DEBUG")
    logger.addHandler(logging.StreamHandler())

    exe = psij.JobExecutor.get_instance("local")
    job = psij.Job(psij.JobSpec("test", "echo", arguments=["foo"]))
    exe.submit(job)

    # This hangs
    job.wait()

if __name__ == "__main__":
    # `fork` hangs, `spawn` and `forkserver` work as expected
    set_start_method("fork")
    unused_exe = psij.JobExecutor.get_instance("local")
    p = Process(target=func)
    p.start()
    p.join()

```

Second, when using threading, #388 forces the instantiation of the executor in the main thread because signal handlers cannot be created in a child thread. For example this will cause an error:

```python
#!/usr/bin/env python3

import logging
from threading import Thread
import psij


def func():
    # Get logs from PSI/J
    logger = logging.getLogger()
    logger.setLevel("DEBUG")
    logger.addHandler(logging.StreamHandler())

    exe = psij.JobExecutor.get_instance("local")
    job = psij.Job(psij.JobSpec("test", "echo", arguments=["foo"]))
    exe.submit(job)

    # This hangs
    job.wait()

if __name__ == "__main__":
    p = Thread(target=func)
    p.start()
    p.join()

```
I was able to work around these problems for my use cases, but I'm not quite familiar enough with this code base to have a good idea on how to fix it though.

**Comment by hategan** [comment]
Thanks for the updates. There are some changes that might help in #390. Please give that a try.

However, it is impossible to make things work in all scenarios. In particular:
- signal handlers can only be attached from the main Python thread, but there is no way to guarantee that a particular call in a library is only run from the main thread (unless you guard it with a specific check, which #390 does).
- fork() and multithreading do not work together, and I quote from the `fork()` man page:
     > After a fork() in a multithreaded program, the child can safely call only async-signal-safe functions (see signal-safety(7)) until such time as it calls execve(2).

  Similarly, the Python documentation states:
     > Note that safely forking a multithreaded process is problematic.

  so `fork()` is not meant to be used for much except `exec*`. PR #390 makes the test cases in this issue work, but it is impossible, in general, to guarantee that PSI/J (or any multithreaded library) will work with `fork()`.

**Comment by hategan** [comment]
@tlhr, do you have any comments on PR #390? Would you like to try it with your setup?

**Comment by tlhr** [comment]
@hategan, sorry for the late reply, and thanks a lot for this fix. It indeed solves the issue :)
