### ISSUE TITLE
Documentation: Example for how to load modules

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [ExaWorks/psij-python#402]
Most HPC workflows involve the loading of various system-supported modules (e.g. `module load vasp`). Since this is such a common usage pattern, it's probably worth having a brief section in the docs about how to do this. Presumably, the recommended approach is to use the `pre_launch` kwarg with a Bash file containing the commands for the modules to load.

The same could be said for many other scenarios of course, such as loading a remote Conda environment.

**Comment by hategan** [comment]
#411 now contains a section on how to do a basic module load in the user guide.

**Comment by Andrew-S-Rosen** [comment]
Beautiful!!
