### ISSUE TITLE
Incorrect job duration formatting for SLURM

### ISSUE THREAD

**Issue by tlhr** [ExaWorks/psij-python#407]
It seems that job time durations longer than one day are not formatted correctly, causing job submission errors. Here's an example:

```python
from datetime import timedelta
from psij import Job, JobSpec
from psij.job_attributes import JobAttributes
from psij.job_executor import JobExecutor

job = Job(JobSpec(executable='/bin/date', attributes=JobAttributes(duration=timedelta(days=2))))
ex = JobExecutor.get_instance("slurm")
ex.submit(job)
status = job.wait(timeout=5)
```

The generated SLURM script then has this time entry: `#SBATCH --time='2 days, 0:00:00'`, which doesn't conform to the [SLURM time format](https://slurm.schedmd.com/sbatch.html#OPT_time) and results in an `Invalid --time specification` error.

The issue seems to be in the `__repr__` method of the `JobAttributes` class, I guess we would need some custom `timedelta` formatter dependent on the batch system here? This might also effect batch systems other than SLURM, but I don't have access to anything else at the moment. I'd be happy to work on a fix, but I'm not quite sure what the best place for this would be, as `JobAttributes` is batch system agnostic.

**Comment by hategan** [comment]
Fixed in #409.
