### ISSUE TITLE
Some words are cut off on PSI/J Python Webpage

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [ExaWorks/psij-python#417]
https://exaworks.org/psij-python/

"here [sic] is no need to wait for infrequent deployment cycles. The HPC world"

Also, the left and middle context info block are cut off at the end.
![image](https://github.com/ExaWorks/psij-python/assets/8674072/064c4a1a-6e75-4c77-b3df-58cff58d0e47)

**Comment by hategan** [comment]
This is my doing. Thank you for spotting this. Fix is in #418.
