### ISSUE TITLE
Next steps for a new release? 

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [ExaWorks/psij-python#422]
Hi all! It's been quite a while since the last PyPI release, with many important updates and bug fixes since. I am opening this issue to inquire about what the next steps are to get the repo in the proper shape for a new release. Are there any roadblocks? Perhaps I can help in my spare time if there are some low hanging fruit.

**Comment by Andrew-S-Rosen** [comment]
Thanks for the reply! That's quite useful to know. I certainly am looking forward to file staging features, but I agree that it would likely still be worthwhile to release another 0.9x version in the meantime.

> Speaking of the testing server, once we merge and deploy the changes, would you be willing to add nightly tests for resources you have access to?

While I can't guarantee anything in particular, I would certainly be open to considering it. That said, the only machine I currently have access to is Perlmutter at NERSC, which perhaps you are already testing nightly. When I start at Princeton as a faculty member in the summer though, there are some local HPC options there that would perhaps be useful.

**Comment by hategan** [comment]
I think we can close this for now. A number of 0.9x releases have happened since and we do make releases whenever a sufficient number of fixes accumulate.
