### ISSUE TITLE
Not able to get ResourceSpecV1 working with PBS

### ISSUE THREAD

**Issue by mike406** [ExaWorks/psij-python#434]
Just checking to see if I am just doing something wrong or not but I am not able to get a PBS select string any different than `1:ncpus=1` no matter what resource spec I give to the job. Is this a known issue?

**Comment by hategan** [comment]
I am not entirely sure what you mean, but I'm guessing that the complaint is that you are only getting one process started on one node. Could it be because of `launcher='single'`? May I suggest either the `multiple` launcher or `mpirun`?

**Comment by mike406** [comment]
So this is my quick example I was testing with. I had thought that this example would select 2 nodes. Am I doing something incorrect?

```
from psij import Job, JobExecutor, JobAttributes, JobSpec, ResourceSpec, ResourceSpecV1
from psij.executors.batch.batch_scheduler_executor import BatchSchedulerExecutorConfig
from pathlib import Path
from datetime import timedelta
import logging

logging.basicConfig(level=logging.DEBUG)

working_directory = "/home/user/psi/test_runs/test"


ex = JobExecutor.get_instance(
    name="pbs",
    config=BatchSchedulerExecutorConfig(
        launcher_log_file=Path(working_directory) / "job.log",
        work_directory=Path(working_directory),
        initial_queue_polling_delay=2,
        queue_polling_error_threshold=2,
        keep_files=True
    )
)

job_attributes = JobAttributes(
    duration=timedelta(minutes=60),
    project_name="test_proj",
)

job_resources = ResourceSpecV1(
    node_count=2,
    processes_per_node=4,
)

job_spec = JobSpec(
    name="test_job",
    executable="/bin/date",
    attributes=job_attributes,
    resources=job_resources,
    stdout_path=Path(working_directory) / "job.out",
    stderr_path=Path(working_directory) / "job.err",
    launcher="multiple"
)

job = Job(job_spec)

ex.submit(job)
```

**Comment by hategan** [comment]
Well, this is embarrassing. The PBS job template says: `# TODO: job.spec.resources`. I will work on fixing this and hopefully have a fix and release early next week.

**Comment by mike406** [comment]
Aha! No worries, I just was unsure if I was making a newbie mistake. I appreciate it!
