### ISSUE TITLE
Account vs. project

### ISSUE THREAD

**Issue by hategan** [ExaWorks/psij-python#456]
PBS distinguishes between an account (`-A` option) and a project (`-P` option). At least one system (improv@lcrc.anl) needs the account to be set to what the allocation system calls a "project". The current executor, on the other hand, maps `spec.project` to `-P`.

Anyway, we have two things, and only one of them is supported by the job spec, so we probably need to decide whether to amend the specification to account for both.

@andre-merzky, thoughts?

**Comment by hategan** [comment]
One note, when setting `-P` on improv, qsub fails with 'The project cannot be set by qsub`. The PBS documentation (https://2021.help.altair.com/2021.1/PBSProfessional/PBSReferenceGuide2021.1.pdf) is not entirely clear (to me at least) on which is which and what the purpose of `-P` is, but it does mildly suggest that `-A` is what should be used for accounting purposes.

**Comment by andre-merzky** [comment]
Follow-up from the call: I  was a bit off with my pbs statement: SAGA did this:
```py
        if 'PBSPro_1' in pbs_version:
            # On PBS Pro we set both -P(roject) and -A(accounting),
            # as we don't know what the admins decided, and just
            # pray that this doesn't create problems.
            pbs_params += "#PBS -P %s \n" % str(jd.project)
            pbs_params += "#PBS -A %s \n" % str(jd.project)
        else:
            # Torque
            pbs_params += "#PBS -A %s \n" % str(jd.project)
```
Apparently this would not have worked on improv :stuck_out_tongue:

The parsing of project was something we had on slurm where we used it to specify a 'reservation':
```py
        if project and ':' in project:
            account, reservation = project.split(':', 1)
        else:
            account, reservation = project, None
[...]

        if account     : script += '#SBATCH --account "%s"\n'     % account
        if reservation : script += '#SBATCH --reservation "%s"\n' % reservation
```
Either way though: what you propose (rename to 'account' ) seems reasonable - this is used for accounting after all.   Being able to set 'project' with something like `jobspec.account = 'my_account:my_project'` for machines where this is needed sounds still reasonable to me.  But if one machine only needs 'project', then that would end up as `jobspec.account = ':my_project'`  which is ok if it happens rarely, but not so ok if that happens very frequently I guess.
