### ISSUE TITLE
Dependency on typeguard 2.12 conflicts with other packages.

### ISSUE THREAD

**Issue by hjjvandam** [ExaWorks/psij-python#461]
At present psij-python has typeguard 2.12 as a requirement (see requirements.txt). This causes conflicts with other packages that have moved on to typeguard > 3.0.1. However the required changes seem minimal. 

Using typeguard 2.12 you would write:
```python
from typeguard import check_argument_types
...
def function(...):
    ...
    assert check_argument_types()
    ...
```
Using typeguard > 3.0.1 this becomes:
```python
from typeguard import typechecked
...
@typechecked
def function(...):
```
So far I have found 3 locations where this change needs to be made:

- src/psij/job_attributes.py
- src/psij/job_spec.py
- src/psij/resource_spec.py

Given that the require modifications seem minimal, and that the old typeguard 2.12 is incompatible with the post typeguard 3.0.1 versions, would it make sense to make these changes and update the version of typeguard that psij-python depends on?

**Comment by andre-merzky** [comment]
Hey @hjjvandam - thanks for digging into that and providing that level of detail!

**Comment by andre-merzky** [comment]
Nothing is ever easy, right? :-P  So the changes are simple enough, but mypy does not handle decorated methods well enough unless the decorators have been carefully type annotated - and ironically, `@typechecked` is not of that kind, and thus using `@typechecked` fails the mypy type check.  Hahahaha ;-)  Please allow some time to look into this a bit closer to see if we can find a way which does not disable either check in that specific place.

**Comment by hjjvandam** [comment]
Thanks Andre. Personally I have never used mypy before. Is that being used in the continuous integration testing? 
What I have seen so far from type checking in Python is that it still is a rather new concept and the technology is still rather fluid. I like the idea though. I'll also see if I can find a minute to look into this a bit more.
