### ISSUE TITLE
Deprecation warning for "project_name" is always triggered

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [ExaWorks/psij-python#468]
With psij-python 0.9.7:

```python
from psij.job_attributes import JobAttributes
JobAttributes()
```

Returns:

```
The "project_name" attribute is deprecated. Please use the "account" attribute instead.
```

The same thing happens when `account` is directly provided. Presumably, this is because "project_name" is being set in the init? I haven't looked into this deeply.

**Comment by hategan** [comment]
Fixed by #469.
