### ISSUE TITLE
RCT integration: remote submission

### ISSUE THREAD

**Issue by andre-merzky** [ExaWorks/psij-python#74]
TO integrate PSI-J with RCT, PSI-J would need the ability to submit jobs remotely, usually over an ssh connection.

**Comment by wilke** [comment]
Still in progress

**Comment by andre-merzky** [comment]
This does in principle work now as the [ZMQ executor](https://github.com/ExaWorks/psij-zmq) exists and works and the [REST executor](https://github.com/ExaWorks/psij-rest) is on it's way.  It is not a turnkey solution as the service bootstrapping is missing - that will be covered in #342 and I close this ticket in favor of it.
